<?php return array (
  'time' => '02071532',
  'totals' => 
  array (
  ),
  'all' => 
  array (
    0 => 
    array (
      'user' => '2892572590',
      'screen_name' => 'd7606f548a50476',
      'text' => 'RT @elpaissemanal: Mañana son los #PremiosGoya. ¿Conoces a los "Héroes de la taquilla"?  Por @gbelinchon http://t.co/rKCaNFyMFs http://t.co…',
      'id' => '563771752678166528',
      'link' => 'http://twitter.com/d7606f548a50476/status/563771752678166528',
      'net' => 'tw',
      'media' => 
      array (
        0 => 'http://pbs.twimg.com/media/B9K9kw4CUAAkYNe.jpg',
      ),
      'tags' => 
      array (
      ),
      'userData' => 
      array (
        'name' => 'Evita García',
        'screen_name' => 'd7606f548a50476',
        'location' => 'BCN',
        'followers_count' => 11,
        'profile_image_url' => 'http://pbs.twimg.com/profile_images/541396102004891649/tjC1PxA3_normal.jpeg',
        'net' => 'tw',
      ),
      'type' => 'img-big',
    ),
    1 => 
    array (
      'user' => '214226418',
      'screen_name' => 'Gervasito',
      'text' => 'RT @carminayamen: ¡¡Y mañana los #PremiosGoya!! Deseadnos suerte con esa nominación para Yolanda Barros como Actriz Revelación! http://t.co…',
      'id' => '563775479724142593',
      'link' => 'http://twitter.com/Gervasito/status/563775479724142593',
      'net' => 'tw',
      'media' => 
      array (
        0 => 'http://pbs.twimg.com/media/B9AzISuIIAEkLOs.jpg',
      ),
      'tags' => 
      array (
      ),
      'userData' => 
      array (
        'name' => 'Gervasio Iglesias',
        'screen_name' => 'Gervasito',
        'location' => 'Sevilla, spain',
        'followers_count' => 4395,
        'profile_image_url' => 'http://pbs.twimg.com/profile_images/539923181206003712/B3WCRGe7_normal.jpeg',
        'net' => 'tw',
      ),
      'type' => 'img-big',
    ),
    2 => 
    array (
      'user' => '346623084',
      'screen_name' => 'clarigam',
      'text' => 'RT @VogueSpain: #BarbaraLennie tiene el \'pixie\' más cool y sabemos cómo lo peinará mañana en los #Goya2015 http://t.co/qFRmIt4Xzl http://t.…',
      'id' => '563775299910135808',
      'link' => 'http://twitter.com/clarigam/status/563775299910135808',
      'net' => 'tw',
      'media' => 
      array (
        0 => 'http://pbs.twimg.com/media/B9KMRMdIUAApHeB.jpg',
      ),
      'tags' => 
      array (
      ),
      'userData' => 
      array (
        'name' => 'Clara',
        'screen_name' => 'clarigam',
        'location' => 'Buenos Aires',
        'followers_count' => 604,
        'profile_image_url' => 'http://pbs.twimg.com/profile_images/544591201291468800/BQiMsimp_normal.jpeg',
        'net' => 'tw',
      ),
      'type' => 'img-big',
    ),
    3 => 
    array (
      'user' => '265596870',
      'screen_name' => 'danicorderom',
      'text' => 'RT @SabloPola: La @ComunidadMadrid subvencionará largometrajes y suprimirá las tasas para rodar en @metro_madrid #Goya2015 #Cine http://t.c…',
      'id' => '563785304898027520',
      'link' => 'http://twitter.com/danicorderom/status/563785304898027520',
      'net' => 'tw',
      'media' => 
      array (
        0 => 'http://pbs.twimg.com/media/B9LG25jIEAEun35.jpg',
      ),
      'tags' => 
      array (
      ),
      'userData' => 
      array (
        'name' => 'Daniel Cordero M',
        'screen_name' => 'danicorderom',
        'location' => '#Coslada #Madrid #España',
        'followers_count' => 3561,
        'profile_image_url' => 'http://pbs.twimg.com/profile_images/558960808873709569/_n3cxRLt_normal.jpeg',
        'net' => 'tw',
      ),
      'type' => 'img-big',
    ),
    4 => 
    array (
      'user' => '811707462',
      'screen_name' => 'Paublanc17',
      'text' => 'RT @mizonatv: La fiesta de los #Goya2015, presentada por @DANIROVIRA, se vivirá en directo en @rtve http://t.co/e485c7l7LX http://t.co/cZWj…',
      'id' => '563784823098335234',
      'link' => 'http://twitter.com/Paublanc17/status/563784823098335234',
      'net' => 'tw',
      'media' => 
      array (
        0 => 'http://pbs.twimg.com/media/B9LzgDkIEAAlasu.jpg',
      ),
      'tags' => 
      array (
      ),
      'userData' => 
      array (
        'name' => 'Pau',
        'screen_name' => 'Paublanc17',
        'location' => 'Vigo',
        'followers_count' => 827,
        'profile_image_url' => 'http://pbs.twimg.com/profile_images/539922690598252544/GXAv0SNY_normal.jpeg',
        'net' => 'tw',
      ),
      'type' => 'img-big',
    ),
    5 => 
    array (
      'user' => '57983020',
      'screen_name' => 'la2_tve',
      'text' => '¿Cuáles son los comentarios y análisis más ingeniosos? ¿Cuál es la mejor película para los tuiteros ?  http://t.co/rVouQ0att3 #GoyasGolfos',
      'id' => '563784480440074241',
      'link' => 'http://twitter.com/la2_tve/status/563784480440074241',
      'net' => 'tw',
      'tags' => 
      array (
        0 => 'Academia de cine',
        1 => 'Adrian Lastra',
        2 => 'Adrian Rodriguez',
        3 => 'Adriana Abenia',
        4 => 'Adriana Ozores',
        5 => 'Adriana Ugarte',
        6 => 'Agustín Almodovar',
        7 => 'Aitana Sánchez Gijón',
        8 => 'Aitor Luna',
        9 => 'Alberto Ammann',
        10 => 'Alberto Rodríguez',
        11 => 'Alejandro Amenábar',
        12 => 'Alex de la Iglesia',
        13 => 'Alex Gonzalez',
        14 => 'Alex O’Dogherty',
        15 => 'Almudena Cid',
        16 => 'Amaia Salamanca',
        17 => 'Ana Belén',
        18 => 'Ana de Armas',
        19 => 'Ana Fernández',
        20 => 'Ana Fernández',
        21 => 'Ana Locking',
        22 => 'Ana Millán',
        23 => 'Ana Polvorosa',
        24 => 'Andrea Duro',
        25 => 'Andrés Velencoso',
        26 => 'Angeles Gonzalez Sinde',
        27 => 'Antonia San Juan',
        28 => 'Antonio Banderas',
        29 => 'Antonio de la Torre',
        30 => 'Antonio Resines',
        31 => 'Antonio Velázquez',
        32 => 'Antonio Zabalburu',
        33 => 'Aristocrazy Joyas',
        34 => 'Asier Etxeandia',
        35 => 'Asociación de Creadores de la Moda',
        36 => 'Assumpta Serna',
        37 => 'Aída Folch',
        38 => 'Beatriz Peñalver',
        39 => 'Beatriz Sanchís',
        40 => 'Begoña Maestre',
        41 => 'Belén Rueda',
        42 => 'Bernabé Fernández',
        43 => 'Bibiana Fernández',
        44 => 'Bimba Bosé',
        45 => 'Blanca Romero',
        46 => 'Blanca Suárez',
        47 => 'Boris Izaguirre',
        48 => 'Borja Cobeaga',
        49 => 'Bárbara Goenaga',
        50 => 'Bárbara Lennie',
        51 => 'Bárbara Lennie',
        52 => 'Canco Rodriguez',
        53 => 'Candela Peña',
        54 => 'Carles Francino',
        55 => 'Carlos Areces',
        56 => 'Carlos Marques-Marcet',
        57 => 'Carlos Santos',
        58 => 'Carlos Santos',
        59 => 'Carlos Vermut',
        60 => 'Carlotta Cosials',
        61 => 'Carmen Machi',
        62 => 'Carmen Ruiz',
        63 => 'Carolina Bang',
        64 => 'Carrera y Carrera',
        65 => 'Cayetana Guillén Cuervo',
        66 => 'Cecilia Gessa',
        67 => 'Celia Freijeiro',
        68 => 'Celia Freijeiro',
        69 => 'Christian Galvez',
        70 => 'Clara Lago',
        71 => 'Clara Lago',
        72 => 'Concha Velasco',
        73 => 'Cosmopolitan',
        74 => 'Crawford',
        75 => 'Cristina Pedroche',
        76 => 'Curro Sánchez Varela',
        77 => 'Dafne Fernández',
        78 => 'Damián Szifrón',
        79 => 'Dani Rovira',
        80 => 'Dani Rovira',
        81 => 'Daniel Galindo',
        82 => 'Daniel Guzman',
        83 => 'Daniel Monzón',
        84 => 'David Bustamente',
        85 => 'David Delfin',
        86 => 'David Delfin',
        87 => 'David Demaría',
        88 => 'David Martos',
        89 => 'David Verdaguer',
        90 => 'DevotayLomba',
        91 => 'Diana Aller',
        92 => 'Diana Palazón',
        93 => 'Dolores promesas',
        94 => 'Eduard Fernández',
        95 => 'Eduardo Casanova',
        96 => 'Eduardo Noriega',
        97 => 'El Langui',
        98 => 'Elena Anaya',
        99 => 'Elena Furiase',
        100 => 'Elia Galera',
        101 => 'Elle España',
        102 => 'Ernesto Alterio',
        103 => 'Ernesto Alterio',
        104 => 'Estrella Morente',
        105 => 'Eva Hache',
        106 => 'Fele Martínez',
        107 => 'Fer de Luis-Orueta',
        108 => 'Fernando Guillén Cuervo',
        109 => 'Fernando Tejero',
        110 => 'Fran Perea',
        111 => 'Félix Gómez',
        112 => 'GermainedeCapuccini',
        113 => 'GHD',
        114 => 'Glamoour España',
        115 => 'Gloria Campos',
        116 => 'Gorka Otxoa',
        117 => 'Goya Toledo',
        118 => 'Grazia',
        119 => 'Hector Samblás',
        120 => 'Hiba Abouk',
        121 => 'Hugo Silva',
        122 => 'India Martínez',
        123 => 'Ingrid García Jonsson',
        124 => 'Irene Escolar',
        125 => 'Irene Montala',
        126 => 'Irene Ortega',
        127 => 'Irene Visedo',
        128 => 'Ismael Recio',
        129 => 'Israel Elejalde',
        130 => 'Iván Sánchez',
        131 => 'Jairo Alonso',
        132 => 'Javier Gutiérrez',
        133 => 'Javier Reyes',
        134 => 'Jesús Castro',
        135 => 'Jesús Olmedo',
        136 => 'Jorge Drexler',
        137 => 'Jose Coronado',
        138 => 'Jose Luis Díez',
        139 => 'José Corbacho',
        140 => 'José Luis Cuerda',
        141 => 'José Sacristán',
        142 => 'Joyería Yanes',
        143 => 'Juan Antonio Bayona',
        144 => 'Juana Acosta',
        145 => 'Juanfer Andrés y Esteban Roel',
        146 => 'Juanjo Oliva',
        147 => 'Judith Colell',
        148 => 'Judith Colell',
        149 => 'Julián López',
        150 => 'Karra Elejalde',
        151 => 'Kira Miró',
        152 => 'Leire Martínez',
        153 => 'Leonor Watling',
        154 => 'Leticia Dolera',
        155 => 'Lolita',
        156 => 'Lolita Make Up Artist',
        157 => 'LOréal Professionnel',
        158 => 'Lucía Jiménez',
        159 => 'Luis Bermejo',
        160 => 'Luis Callejo',
        161 => 'Luis Ivars',
        162 => 'Lujan Argüelles',
        163 => 'Macaco',
        164 => 'Macarena García',
        165 => 'Macarena Gómez',
        166 => 'Malena Costa',
        167 => 'Manuela Velasco',
        168 => 'Manuela Vellés',
        169 => 'Mar Saura',
        170 => 'Mariam Hernández',
        171 => 'Mario Casas',
        172 => 'Marisa Paredes',
        173 => 'Marta Etura',
        174 => 'Marta Hazas',
        175 => 'Marta Larralde',
        176 => 'Martin Rivas',
        177 => 'María Adanez',
        178 => 'María León',
        179 => 'María Valverde',
        180 => 'MAS TVE',
        181 => 'Maxi Iglesias',
        182 => 'Mercedes León',
        183 => 'Mesala Films',
        184 => 'Michelle Jenner',
        185 => 'Miguel Angel Silvestre',
        186 => 'miguel poveda',
        187 => 'Miguel Ángel Muñoz',
        188 => 'Miriam Díaz-Aroca',
        189 => 'Miriam Giovanelli',
        190 => 'Montxo Armendariz',
        191 => 'Nacho Vigalondo',
        192 => 'Natalia Belda',
        193 => 'Natalia Tena',
        194 => 'Natalia Verbeke',
        195 => 'Natasha Yarovenko',
        196 => 'Nathalie Pozas',
        197 => 'Nerea Barros',
        198 => 'Nerea Garmendia',
        199 => 'Nieves Álvarez',
        200 => 'Norma Ruiz',
        201 => 'Nuria Gago',
        202 => 'Oscar Jaenada',
        203 => 'Pablo Berger',
        204 => 'Pablo Carbonell',
        205 => 'Pablo Derqui',
        206 => 'Paco Cabezas',
        207 => 'Paco León',
        208 => 'Paco Tous',
        209 => 'Paloma Molinero',
        210 => 'Paula Echevarría',
        211 => 'Pelayo Díaz',
        212 => 'Pepino Marino',
        213 => 'Pilar Castro',
        214 => 'Pilar Rubio',
        215 => 'Premios Feroz',
        216 => 'Premios Goya',
        217 => 'Quim Gutierrez',
        218 => 'Rafa Muñoz',
        219 => 'Rafa Muñoz',
        220 => 'Raúl Arévalo',
        221 => 'Revista GQ',
        222 => 'Ricardo Darín',
        223 => 'Roberto Verino',
        224 => 'Rodrigo Cortés',
        225 => 'Rossy de Palma',
        226 => 'Rubén Ochandiano',
        227 => 'Salón Cheska',
        228 => 'Sandra Cervera',
        229 => 'Santi Millan',
        230 => 'Santiago Segura',
        231 => 'Secun de la Rosa',
        232 => 'Sergio Pazos',
        233 => 'Silvia Abascal',
        234 => 'Silvia Alonso',
        235 => 'Sr Paco Tomás',
        236 => 'Telva',
        237 => 'Toni Acosta',
        238 => 'Tristán Ulloa',
        239 => 'Unax Ugalde',
        240 => 'Vanity Fair',
        241 => 'Verónica Echegui',
        242 => 'Verónica Forqué',
        243 => 'Verónica Sánchez',
        244 => 'Vogue',
        245 => 'Víctor Blanco',
        246 => 'William Miller',
        247 => 'Yodona',
        248 => 'Yolanda Ramos',
        249 => 'Álex García',
        250 => 'Álvaro Cervantes',
        251 => 'Úrsula Corberó',
        252 => 'Penélope Cruz',
        253 => 'Javier Bardem',
      ),
      'userData' => 
      array (
        'name' => 'La 2 de TVE',
        'screen_name' => 'la2_tve',
        'location' => '',
        'followers_count' => 163119,
        'profile_image_url' => 'http://pbs.twimg.com/profile_images/322579325/tve2_normal.png',
        'net' => 'tw',
      ),
      'type' => 'txt',
    ),
    6 => 
    array (
      'user' => '2313411439',
      'screen_name' => 'lopezdeaudicana',
      'text' => 'RT @PasaporteAnd: Visita nuestro especial de @LaIslaMinima http://t.co/LySoJDmC7x X @JuanmiBaquero y @maparranguita #goyas2015 http://t.co/…',
      'id' => '563782914543206400',
      'link' => 'http://twitter.com/lopezdeaudicana/status/563782914543206400',
      'net' => 'tw',
      'media' => 
      array (
        0 => 'http://pbs.twimg.com/media/B9Lxn7xIIAAo8Vr.jpg',
      ),
      'tags' => 
      array (
      ),
      'userData' => 
      array (
        'name' => 'Iñigo ',
        'screen_name' => 'lopezdeaudicana',
        'location' => '',
        'followers_count' => 81,
        'profile_image_url' => 'http://pbs.twimg.com/profile_images/506422709027237888/V2-Xs-HX_normal.jpeg',
        'net' => 'tw',
      ),
      'type' => 'img-big',
    ),
    7 => 
    array (
      'user' => '379663040',
      'screen_name' => '1992_anna_',
      'text' => 'RT @mizonatv: La fiesta de los #Goya2015, presentada por @DANIROVIRA, se vivirá en directo en @rtve http://t.co/e485c7l7LX http://t.co/cZWj…',
      'id' => '563781055141142528',
      'link' => 'http://twitter.com/1992_anna_/status/563781055141142528',
      'net' => 'tw',
      'media' => 
      array (
        0 => 'http://pbs.twimg.com/media/B9LzgDkIEAAlasu.jpg',
      ),
      'tags' => 
      array (
      ),
      'userData' => 
      array (
        'name' => 'Anna aria',
        'screen_name' => '1992_anna_',
        'location' => 'Madrid',
        'followers_count' => 31,
        'profile_image_url' => 'http://pbs.twimg.com/profile_images/554007916546883586/Pf8EBZE__normal.jpeg',
        'net' => 'tw',
      ),
      'type' => 'img-big',
    ),
    8 => 
    array (
      'user' => '18979745',
      'screen_name' => 'ppmadrid',
      'text' => 'RT @SabloPola: La @ComunidadMadrid subvencionará largometrajes y suprimirá las tasas para rodar en @metro_madrid #Goya2015 #Cine http://t.c…',
      'id' => '563780712030285824',
      'link' => 'http://twitter.com/ppmadrid/status/563780712030285824',
      'net' => 'tw',
      'media' => 
      array (
        0 => 'http://pbs.twimg.com/media/B9LG25jIEAEun35.jpg',
      ),
      'tags' => 
      array (
      ),
      'userData' => 
      array (
        'name' => 'PP de Madrid',
        'screen_name' => 'ppmadrid',
        'location' => 'Madrid, España',
        'followers_count' => 34798,
        'profile_image_url' => 'http://pbs.twimg.com/profile_images/482858149976621056/2KintKIi_normal.png',
        'net' => 'tw',
      ),
      'type' => 'img-big',
    ),
    9 => 
    array (
      'user' => '149490792',
      'screen_name' => 'diegociempo2000',
      'text' => 'RT @PremiosGoyaEs: El Langui no se perderá la gala de los #Goyas2015 y entregará uno de los premios.
@Langui_Oficial 
#Goyas2015 http://t.c…',
      'id' => '563780657596616705',
      'link' => 'http://twitter.com/diegociempo2000/status/563780657596616705',
      'net' => 'tw',
      'media' => 
      array (
        0 => 'http://pbs.twimg.com/media/B9LdXwGCYAEIhDO.png',
      ),
      'tags' => 
      array (
      ),
      'userData' => 
      array (
        'name' => '聖地亞哥',
        'screen_name' => 'diegociempo2000',
        'location' => 'Ciempozuelos, Madrid',
        'followers_count' => 291,
        'profile_image_url' => 'http://pbs.twimg.com/profile_images/502240676038586368/EKJ9JizF_normal.jpeg',
        'net' => 'tw',
      ),
      'type' => 'img-big',
    ),
    10 => 
    array (
      'user' => '2961808767',
      'screen_name' => 'sofiescorbuto',
      'text' => 'RT @Ayto_Sevilla: Homenaje a los sevillanos nominados a los #PremiosGoya en el @Ayto_Sevilla #Sevillahoy http://t.co/dMq0PTfSXm http://t.co…',
      'id' => '563780292700565505',
      'link' => 'http://twitter.com/sofiescorbuto/status/563780292700565505',
      'net' => 'tw',
      'media' => 
      array (
        0 => 'http://pbs.twimg.com/media/B9KWeFAIYAAavBX.jpg',
      ),
      'tags' => 
      array (
      ),
      'userData' => 
      array (
        'name' => 'Sofia escorbuto',
        'screen_name' => 'sofiescorbuto',
        'location' => '',
        'followers_count' => 10,
        'profile_image_url' => 'http://pbs.twimg.com/profile_images/559346979210539009/Wox0gFR5_normal.jpeg',
        'net' => 'tw',
      ),
      'type' => 'img-big',
    ),
    11 => 
    array (
      'user' => '416693314',
      'screen_name' => 'MariaVarod',
      'text' => 'RT @carminayamen: ¡¡Y mañana los #PremiosGoya!! Deseadnos suerte con esa nominación para Yolanda Barros como Actriz Revelación! http://t.co…',
      'id' => '563784703745196032',
      'link' => 'http://twitter.com/MariaVarod/status/563784703745196032',
      'net' => 'tw',
      'media' => 
      array (
        0 => 'http://pbs.twimg.com/media/B9AzISuIIAEkLOs.jpg',
      ),
      'tags' => 
      array (
      ),
      'userData' => 
      array (
        'name' => 'María Varod',
        'screen_name' => 'MariaVarod',
        'location' => '',
        'followers_count' => 112,
        'profile_image_url' => 'http://pbs.twimg.com/profile_images/378800000581929971/f3c5ac43d9fbe7b71bdfca4b380b073f_normal.jpeg',
        'net' => 'tw',
      ),
      'type' => 'img-big',
    ),
  ),
  'minute' => 
  array (
  ),
) ;